### ISSUE TITLE
`@types/shexj` doesn't have a corresponding package `shexj` on npm

### ISSUE THREAD

**Issue by mrkvon** [shexjs/shex.js#239]
## Description of problem

It seems that [@types/shexj](https://www.npmjs.com/package/@types/shexj) doesn't have a corresponding package [shexj](https://www.npmjs.com/package/shexj) published on npmjs.com.

The types can still be imported in projects, e.g. in [this](https://github.com/search?q=repo%3Ashexjs%2Fshex.js+%22import+*+as+ShExJ+from+%27shexj%27%3B%22&type=code) and other libraries:

```ts
import * as ShExJ from 'shexj';

// use e.g. type ShExJ.Schema somewhere here
```

But this situation seems non-standard, and personally i find it confusing.

Is it intentional, or is the `@types/shexj` package a leftover from some historic package?

I'm opening the issue here, since this seems the most relevant repository i could find, and it seems that authors/maintainers overlap @ericprud 

This doesn't cause me any issues. I bumped into this when resolving an unrelated issue with eslint rule [`import/no-unresolved`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-unresolved.md). Just curious i guess... 🙂

**Comment by ericprud** [comment]
@types/shexj is meant to defined a format that's independent of tooling. NPM knows of [6 dependents](https://www.npmjs.com/package/@types/shexj?activeTab=dependents), 3 of which come from this repo.
Should there be a corresponding js module? What should the contents be?

**Comment by mrkvon** [comment]
After analyzing the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/) repository with [npms api](https://api-docs.npms.io/), i can see that there are plenty of types without their corresponding package in the npm registry (\~442 out of 5372 that can be found with [api.npms.io](https://api.npms.io/v2/search?q=scope:types); although real number of `@types/...` is higher (\~8622)).

And like many of them, [@typex/shexj](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b366e9ce58b684bc010c8e4aaa439e280e414dc8/types/shexj/index.d.ts#L1) also says (emphasis mine):

> **Type definitions for non-npm package ShExJ 2.1**
> Project: https://github.com/shexSpec/shex
> Definitions by: Eric Prud'hommeaux <https://github.com/ericprud>
> Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
> TypeScript Version: 4.1

I guess my point is that `import { Schema } from 'shexj'` feels weird, if `shexj` doesn't exist.
Further, i assumed that purpose of DefinitelyTyped was to collect types for existing untyped javascript packages.
My intuition was that types like `shexj` would be better served from another package, like `@shexjs/types` or whatnot...

But it seems that such rule doesn't exist, or is not enforced, and there is probably little to no value of moving `shexj` types away from their current place.

So i guess it is what it is, and this issue can be closed.

For me personally, this was a learning experience... 😄
