### ISSUE TITLE
Incorrect "MissingProperty"

### ISSUE THREAD

**Issue by dpriskorn** [shexjs/shex.js#240]
## Description of problem
See all details https://www.wikidata.org/wiki/User:So9q/shexjs

**URL to affected spec or repo:**
https://www.wikidata.org/wiki/Special:EntitySchemaText/E376

**What happened (e.g., it crashed)?:**
Incorrect validation

**Expected behavior (e.g., it shouldn't crash):**
Correct validation. E.i. complain about missing P137 similar to entityshape and nothing else
![image](https://github.com/shexjs/shex.js/assets/68460690/eb75435f-d455-4ca7-999c-2049bb00a361)

**Optional, steps to reproduce:**

See link above for all steps taken

**Comment by salgo60** [comment]
* Transjön [Q96337385](https://www.wikidata.org/wiki/Q96337385)

**Comment by ericprud** [comment]
The validator was trying to guess the start node. I overrode it with a shapemap:
```
./node_modules/.bin/shex-validate -x https://www.wikidata.org/wiki/Special:EntitySchemaText/E376 -d https://www.wikidata.org/entity/Q96337385.ttl -m 'wd:Q96337385@<campsite>'
```

I got lots of errors but didn't have time to dig in. I typically diagnose by grabbing both the schema and the data and editing them 'till they work

**Comment by salgo60** [comment]
@ericprud thanks the tool is magic

I dont even understand were to look for the Google Map identificator when in Google Map...

**Comment by ericprud** [comment]
> I typically diagnose by grabbing both the schema and the data and editing them 'till they work

Forgot to add that ShExC's block comments (`/*`...`*/`) are your friend here.

Since you +1'd this, I'm closing this issue. Feel free to re-open if I was premature.
