### ISSUE TITLE
The try online wikidata example does not work

### ISSUE THREAD

**Issue by dpriskorn** [shexjs/shex.js#241]
## Description of problem
broken example

**URL to affected spec or repo:**
https://rawgit.com/shexSpec/shex.js/main/packages/shex-webapp/doc/shex-simple.html

**What happened (e.g., it crashed)?:**
clicked wikidata
clicked validate
got
![image](https://github.com/shexjs/shex.js/assets/68460690/5857d63e-d7ea-4667-9ddb-2dda648ca8dc)

**Expected behavior (e.g., it shouldn't crash):**
Something looking like a working example should be displayed

**Optional, steps to reproduce:**

1.  ...

**Comment by ericprud** [comment]
rawgit isn't maintained anymore and tends to rot. (I have no control over that domain or the residual code there.)
try it from https://shex.io/webapps/shex.js/doc/shex-worker.html

Feel free to close this issue.
