### ISSUE TITLE
Error parsing schema

### ISSUE THREAD

**Issue by mistermboy** [shexjs/shex.js#96]
I´m not able to parse the following schema:
```
 PREFIX : <http://www.example.com>
 PREFIX schema:    <http://schema.org/>
 PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>

 :User{
      schema:knows  xsd:string @:User 
  }
```
It throws the following error:
```
Error: undefined(6): Parse error on line 6:
...      schema:knows  xsd:string @:User   }
---------------------------------^
Expecting 'EOF', 'IT_BASE', 'IRIREF', 'IT_PREFIX', 'PNAME_NS', 'IT_IMPORT', 'IT_start', 'IT_OR', 'IT_AND', ')', '.', 'IT_IRI', 'IT_BNODE', 'IT_NONLITERAL', 'INTEGER', 'REGEXP', 'IT_LENGTH', 'IT_MINLENGTH', 'IT_MAXLENGTH', 'DECIMAL', 'DOUBLE', 'STRING', 'IT_MININCLUSIVE', 'IT_MINEXCLUSIVE', 'IT_MAXINCLUSIVE', 'IT_MAXEXCLUSIVE', 'IT_TOTALDIGITS', 'IT_FRACTIONDIGITS', '}', '|', ',', ';', '*', '+', '?', 'REPEAT_RANGE', ']', '~', '-', 'LANGTAG', '//', '%', 'LANG_STRING', 'IT_true', 'IT_false', 'PNAME_LN', 'BLANK_NODE_LABEL', got 'ATPNAME_LN'
...      schema:knows  xsd:string @:User   }
---------------------------------^
    at Object.<anonymous> (D:\Repositories\shexjs\main.js:3:38)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```
I think an "and" keyword is expected between the node constraint and the shapeRef, but the shex grammar allows it to be omitted, doesn't it?

**Comment by ericprud** [comment]
apologies, thought i'd responded earlier.

You need an AND in `xsd:string @AND @:User` ([try it](http://shex.io/webapps/shex.js/doc/shex-simple?schema=%20PREFIX%20%3A%20%3Chttp%3A%2F%2Fwww.example.com%3E%0A%20PREFIX%20schema%3A%20%20%20%20%3Chttp%3A%2F%2Fschema.org%2F%3E%0A%20PREFIX%20xsd%3A%20%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0A%20%3AUser%7B%0A%20%20%20%20%20%20schema%3Aknows%20%20xsd%3Astring%20AND%20%40%3AUser%20%0A%20%20%7D&manifestURL=http%3A%2F%2Fshex.io%2Fwebapps%2Fshex.js%2Fexamples%2Fmanifest.json&interface=human&success=proof&regexpEngine=eval-threaded-nerr))

If you're a fan of grammars, this comes from:

> [45] [tripleConstraint](http://shex.io/shex-semantics/index.html#prod-tripleConstraint) ::= predicate inlineShapeExpression cardinality?
> [11] [inlineShapeExpression](http://shex.io/shex-semantics/index.html#prod-inlineShapeOr) ::= inlineShapeAnd ("OR" inlineShapeAnd)*
> [15] [inlineShapeAnd](http://shex.io/shex-semantics/index.html#prod-inlineShapeAnd) ::= inlineShapeNot ("AND" inlineShapeNot)*                  // <-- `AND`
> [17] [inlineShapeNot](http://shex.io/shex-semantics/index.html#prod-inlineShapeNot) ::= "NOT"? inlineShapeAtom
> [20] [inlineShapeAtom](http://shex.io/shex-semantics/index.html#prod-inlineShapeAtom) ::= nonLitNodeConstraint inlineShapeOrRef?
>                                        | litNodeConstraint
>                                        | inlineShapeOrRef nonLitNodeConstraint?
>                                        | '(' shapeExpression ')'
>                                        | '.'
> [24] [litNodeConstraint](http://shex.io/shex-semantics/index.html#prod-litNodeConstraint) ::= "LITERAL" xsFacet*
>                                        | datatype xsFacet*                                                  // <-- `xsd:string`
>                                        | valueSet xsFacet*
>                                        | numericFacet+
> [22] [inlineShapeOrRef](http://shex.io/shex-semantics/index.html#prod-inlineShapeOrRef) ::= inlineShapeDefinition | shapeRef
> [23] [shapeRef](http://shex.io/shex-semantics/index.html#prod-shapeRef) ::= ATPNAME_LN | ATPNAME_NS | '@' shapeExprLabel      // <-- `@:User`

BTW, you probably want an `OR` instead because nothing is both an `xsd:string` *and* a `:User` ([try it](https://tinyurl.com/t48y9zf3)).

**Comment by mistermboy** [comment]
Thanks for the response. I always thought it was possible to do that in shex :sweat:
